services:
  api:
    image: python:3.11-slim
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./data:/data
    command: >
      bash -lc "pip install -r requirements.txt &&
                uvicorn app.main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  data:
