services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/data
    command: >
      bash -lc "python -m pip install -U pip && pip install -r requirements.txt && cd backend && uvicorn app.main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  data:
