services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    working_dir: /app/backend
    volumes:
      - ./:/app
      - ./data:/data
    command: bash -lc "uvicorn app.main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
  web:
    image: node:20
    working_dir: /app/frontend
    volumes:
      - ./:/app
    command: bash -lc "npm ci || npm i && npm run build && npm run preview -- --host --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  data:
