services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    working_dir: /app/backend
    volumes:
      - ./:/app
      - ./data:/data
    command: bash -lc "uvicorn app.main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  data:
