name: CI Front

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (with cache)
        if: ${{ hashFiles('frontend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Setup Node (no cache fallback)
        if: ${{ hashFiles('frontend/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci || npm i
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint || echo "lint warnings"
      - name: Build
        run: npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: frontend/dist
